import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { NextUIProvider } from '@nextui-org/react';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';
import { SideBar } from '@/components/Sidebar';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Snippets',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body
					className={cn(
						`h-screen w-full flex ${geistSans.variable} ${geistMono.variable} antialiased`,

						{
							'debug-screens': process.env.NODE_ENV === 'development',
						},
					)}
				>
					<ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
						<NextUIProvider>
							<SideBar />

							{/* main page */}
							<div className="p-8 w-full">{children}</div>
						</NextUIProvider>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
